# You can use this docker compose file to pre-seed the solr and blazegraph instances with data
#   usage: docker-compose -f docker-compose.yml -f docker-compose.data.yml <command>

version: '3'

# Use this file to override default, primary configuration in the docker-compose.yml file
# And to load pre-ingested data into it from zip files.
# Example use:
# docker-compose -f docker-compose.yml -f docker-compose.data.yml [command]

services:
