FROM sbtscala/scala-sbt:eclipse-temurin-11.0.16_1.7.2_2.12.17

WORKDIR /hascoapi

COPY . .

RUN apt-get update && \
    apt-get install -y tmux && \
    rm -rf /var/lib/apt/lists/*

RUN sbt update

EXPOSE 9000

CMD ["tmux", "new-session", "-s", "hascoapi", "sbt run"]
